CREATE TABLE TEACHER
(
  TEACHER_ID VARCHAR(25) NOT NULL,
  TEACHER_Name VARCHAR(25) NOT NULL,
  JobType VARCHAR(25) NOT NULL,
  Department VARCHAR(25) NOT NULL,
  Organization VARCHAR(25) NOT NULL,
  PRIMARY KEY (TEACHER_ID)
);

CREATE TABLE TEAM
(
  TEAM_ID VARCHAR(25) NOT NULL,
  TEAM_Name VARCHAR(25) NOT NULL,
  Rank INT,
  Feature VARCHAR(200) NOT NULL,
  TEACHER_ID VARCHAR(25),
  PRIMARY KEY (TEAM_ID),
  FOREIGN KEY (TEACHER_ID) REFERENCES TEACHER(TEACHER_ID)
);

CREATE TABLE WORK
(
  WORK_ID VARCHAR(25) NOT NULL,
  WORK_Name VARCHAR(25) NOT NULL,
  Summary VARCHAR(25) NOT NULL,
  SDGs VARCHAR(25) NOT NULL,
  Poster MEDIUMBLOB NOT NULL,
  WORK_URL VARCHAR(100) NOT NULL,
  Github VARCHAR(100) NOT NULL,
  W_Year YEAR NOT NULL,
  TEAM_ID VARCHAR(25) NOT NULL,
  PRIMARY KEY (WORK_ID),
  FOREIGN KEY (TEAM_ID) REFERENCES TEAM(TEAM_ID)
);

CREATE TABLE JUDGE
(
  J_ID VARCHAR(25) NOT NULL,
  J_Name VARCHAR(25) NOT NULL,
  Title VARCHAR(25) NOT NULL,
  Phone VARCHAR(25) NOT NULL,
  Email VARCHAR(50) NOT NULL,
  PRIMARY KEY (J_ID)
);

CREATE TABLE WORK_SHOP
(
  WS_ID VARCHAR(25) NOT NULL,
  WS_Date DATE NOT NULL,
  WS_Time TIME NOT NULL,
  Topic VARCHAR(25) NOT NULL,
  PRIMARY KEY (WS_ID)
);

CREATE TABLE ADMIN
(
  ADMIN_ID VARCHAR(25) NOT NULL,
  ADMIN_Name VARCHAR(25) NOT NULL,
  Email VARCHAR(50) NOT NULL,
  Phone VARCHAR(25) NOT NULL,
  PRIMARY KEY (ADMIN_ID)
);

CREATE TABLE ANN
(
  ANN_ID VARCHAR(25) NOT NULL,
  Info VARCHAR(25) NOT NULL,
  Poster MEDIUMBLOB NOT NULL,
  ADMIN_ID VARCHAR(25) NOT NULL,
  PRIMARY KEY (ANN_ID),
  FOREIGN KEY (ADMIN_ID) REFERENCES ADMIN(ADMIN_ID)
);

CREATE TABLE GROUP_IDEA
(
  Process VARCHAR(200) NOT NULL,
  NewAttribute VARCHAR(200) NOT NULL,
  Content&Feture VARCHAR(200) NOT NULL,
  Market_Demand VARCHAR(200) NOT NULL,
  Feasibility VARCHAR(200) NOT NULL,
  ExpectBenefit VARCHAR(200) NOT NULL,
  WORK_ID VARCHAR(25) NOT NULL,
  PRIMARY KEY (WORK_ID),
  FOREIGN KEY (WORK_ID) REFERENCES WORK(WORK_ID)
);

CREATE TABLE GROUP_IMPLE
(
  Reason VARCHAR(200) NOT NULL,
  GROUP_Service VARCHAR(200) NOT NULL,
  Market_Demand VARCHAR(200) NOT NULL,
  ExpectBenefit VARCHAR(200) NOT NULL,
  WORK_ID VARCHAR(25) NOT NULL,
  PRIMARY KEY (WORK_ID),
  FOREIGN KEY (WORK_ID) REFERENCES WORK(WORK_ID)
);

CREATE TABLE LECTURER
(
  L_Name VARCHAR(25) NOT NULL,
  Title VARCHAR(50) NOT NULL,
  Phone VARCHAR(25) NOT NULL,
  Email VARCHAR(50) NOT NULL,
  L_Address VARCHAR(50) NOT NULL,
  WS_ID VARCHAR(25) NOT NULL,
  PRIMARY KEY (Name, WS_ID),
  FOREIGN KEY (WS_ID) REFERENCES WORK_SHOP(WS_ID)
);

CREATE TABLE SCORE
(
  Rate INT NOT NULL,
  TEAM_ID VARCHAR(25) NOT NULL,
  J_ID VARCHAR(25) NOT NULL,
  PRIMARY KEY (TEAM_ID, J_ID),
  FOREIGN KEY (TEAM_ID) REFERENCES TEAM(TEAM_ID),
  FOREIGN KEY (J_ID) REFERENCES JUDGE(J_ID)
);

CREATE TABLE HOLD
(
  ADMIN_ID VARCHAR(25) NOT NULL,
  WS_ID VARCHAR(25) NOT NULL,
  PRIMARY KEY (ADMIN_ID, WS_ID),
  FOREIGN KEY (ADMIN_ID) REFERENCES ADMIN(ADMIN_ID),
  FOREIGN KEY (WS_ID) REFERENCES WORK_SHOP(WS_ID)
);

CREATE TABLE MODIFY
(
  ANN_ID VARCHAR(25) NOT NULL,
  ADMIN_ID VARCHAR(25) NOT NULL,
  PRIMARY KEY (ANN_ID, ADMIN_ID),
  FOREIGN KEY (ANN_ID) REFERENCES ANN(ANN_ID),
  FOREIGN KEY (ADMIN_ID) REFERENCES ADMIN(ADMIN_ID)
);

CREATE TABLE STUDENT
(
  S_ID VARCHAR(25) NOT NULL,
  S_Name VARCHAR(25) NOT NULL,
  Sexual VARCHAR(25) NOT NULL,
  Phone VARCHAR(25) NOT NULL,
  Email VARCHAR(50) NOT NULL,
  Department VARCHAR(25) NOT NULL,
  Grade VARCHAR(25) NOT NULL,
  TEAM_ID VARCHAR(25) NOT NULL,
  PRIMARY KEY (S_ID),
  FOREIGN KEY (TEAM_ID) REFERENCES TEAM(TEAM_ID)
);

CREATE TABLE ATTEND
(
  S_ID VARCHAR(25) NOT NULL,
  WS_ID VARCHAR(25) NOT NULL,
  PRIMARY KEY (S_ID, WS_ID),
  FOREIGN KEY (S_ID) REFERENCES STUDENT(S_ID),
  FOREIGN KEY (WS_ID) REFERENCES WORK_SHOP(WS_ID)
);